# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: test-dano

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 2 * * 1-5"

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        node-version: 16.x
        cache: npm
    
    - name: 'hello world'
      run: echo "hello world"
      
    - name: 'current date'
      run: date
    - name: 'list directories'
      run: ls -la
      
    - run: npm ci --legacy-peer-deps
    - run: npm run build --if-present
    - run: npm test
